### ISSUE TITLE
Fatal Error Uncaught InvalidArgumentException: View [partials.headers.woocommerce-header] not found.

### ISSUE THREAD

**Issue by TristanConant** [MarekVrofski/Sage-Woocommerce#1]
First off thank you for taking the time to put this repo together. It's very much appreciated. I found my way here form the Roots discourse forum.

When I attempt to go to a single product page eg: manifestocoffeeroasters.test/product/columbia-cauca I am met with this error:
`Fatal error: Uncaught InvalidArgumentException: View [partials.headers.woocommerce-header] not found. in /home/vagrant/code/gritcity/manifesto/wp-content/themes/manifesto/vendor/illuminate/view/FileViewFinder.php:137 Stack trace: #0 /home/vagrant/code/gritcity/manifesto/wp-content/themes/manifesto/vendor/illuminate/view/FileViewFinder.php(79): Illuminate\View\FileViewFinder->findInPaths('partials.header...', Array) #1 /home/vagrant/code/gritcity/manifesto/wp-content/themes/manifesto/vendor/illuminate/view/Factory.php(128): Illuminate\View\FileViewFinder->find('partials.header...') #2 /home/vagrant/code/gritcity/manifesto/wp-content/uploads/cache/d3ffc3d2e5ce816df6727455888e31ee0e4f2a78.php(1): Illuminate\View\Factory->make('partials.header...', Array) #3 /home/vagrant/code/gritcity/manifesto/wp-content/themes/manifesto/vendor/illuminate/view/Engines/PhpEngine.php(42): include('/home/vagrant/c...') #4 /home/vagrant/code/gritcity/manifesto/wp-content/themes/manifesto/vendor/illuminate/view/Engines/CompilerEngine.php(59): Il in /home/vagrant/code/gritcity/manifesto/wp-content/themes/manifesto/vendor/illuminate/view/FileViewFinder.php on line 137`

When I comment out the 'partials.headers.woocommerce-header' include in archive.-product.blade.php the pages loads fine without getting "Notice: Theme without header.php is deprecated". However is it odd that when I am viewing a single product page it's using the archive template? And I feel like I should not be commenting out the header include. I am pretty sure I added all of the files and snippets from this repo in the proper places. I triple checked them. But that doesn't mean that I am not missing something or messed something up. Any guidance or help would be great. In the mean time am going quadruple check everything haha.

Thank you again for putting this together.

**Comment by MarekVrofski** [comment]
Okay, have you tried creating the missing file? Or include your own header?

When you are viewing a single product, it would normally load `single-product.blade.php` in this file it will search for the file `content-single-product.blade.php`.

I will try to recreate your issue tonight, I can vaguely remember running into the same problem.

**Comment by Twansparant** [comment]
I removed the include line to the **woocommerce-header** partial:
```blade
@include('partials.headers.woocommerce-header')
```
in the following files:
```
resources/views/woocommerce.blade.php
resources/views/woocommerce/archive-product.blade.php
resources/views/woocommerce/single-product.blade.php
```
and things seem to be still working, so I think it's ok to remove them!

**Comment by MarekVrofski** [comment]
@Twansparant I came out with the same result. Thanks for the double check!

@TristanConant Can you post your Woocommerce version, since @Twansparant mentioned in the Roots Discourse forum that he uses a newer version where the files shift around somewhat. 

I think that if you do the same that @Twansparant did your issue will be solved 👍

**Comment by TristanConant** [comment]
@Twansparant I did the same thing last night. :)

@MarekVrofski I am using Version Woocommerce v3.2.6.  There's definitely something odd going on. I have single-product.blade.php and content-single-product.blade.php in partials/woocommerce folder. But my single products are still referencing archive-product.blade. php template. I'll keep fiddling with it this afternoon. Thank you both for the replies.

**Comment by TristanConant** [comment]
Well I am in idiot. I did properly define $template in my single-product.php file...
